### ISSUE TITLE
Unable to start project

### ISSUE THREAD

**Issue by feiyang16886** [GitHubGanKai/vue-jd-h5#59]
Syntax Error: TypeError: Cannot read property 'styles' of undefined
When starting the project(cnpm run dev),report an error ‘Syntax Error: TypeError: Cannot read property 'styles' of undefined’

**Comment by geekskai** [comment]
You can try it with yarn dev, maybe this is the problem！
or see this link  https://github.com/geekskai/vue3-jd-h5/issues/55
