### ISSUE TITLE
宽屏适配

### ISSUE THREAD

**Issue by wswmsword** [GitHubGanKai/vue-jd-h5#72]
你好 Gan Kai，请问考虑宽屏访问吗？如果考虑，可以看下我写的插件，[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)，这个插件不转换 rem，转换 vw，而且不依赖 javascript。如果考虑接入，我可以给你的项目提个 PR。

**Comment by geekskai** [comment]
你好，考虑的，也非常欢迎PR！

**Comment by wswmsword** [comment]
好的😄
